export const MOVIES_BROWSER = {
    GET_MOVIE_LISTING: "GET_MOVIE_LISTING",
    FAILURE_LISTING: "FAILURE_LISTING",
    GET_MOVIE_DETAILS: "GET_MOVIE_DETAILS",
    FAILURE_MOVIE_DETAILS: "FAILURE_MOVIE_DETAILS",
};
